version: "3"

networks:
  core:
    driver: bridge
  site:
    driver: bridge

services:
  db:
    build: ./db
    networks:
      - core
  apparel:
    build: ./apparel
    volumes:
      - ./apparel:/app
    ports:
      - 5001:80
    depends_on:
      - db
    networks:
      - core
  prices:
    build: ./prices
    volumes:
      - ./prices:/app
    ports:
      - 5002:80
    depends_on:
      - apparel
    networks:
      - core
      - site
  site:
    build: ./site
    volumes:
      - ./site:/src
    ports:
      - 5000:80
    depends_on:
      - prices
    networks:
      - site
